import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div>
            <div>
              <label >User</label>
              <input type={'text'} id='user' name='user' placeholder='user'/>
            </div>
            <div>
              <label >Password</label>
              <input type={'password'} id='pass' name='pass' placeholder='password'/>
            </div>
            <div>
              <button type='submit'>Iniciar</button>
            </div>
          </div>
      </main>
    </div>
  )
}
